개발 3주차 코드 리뷰
kakao-tech-campus-2nd-step3/Team10_FE pull request #26
Opened 2024-10-04 14:58 UTC by jasper200207

### 관련 이슈

- #123
- close #1234

### 작업 요약

요약요약

### 작업 상세

- 뭐라뭐라
- 이런저런

### 리뷰 요구 사항

- 리뷰 예상 시간 : 0분
- 이것저것

### 미리 보기

이미지1
이미지2

2024-10-06 05:07 UTC, minsekim1 commented on src/assets/Image/Intro/Intro1.png
public에 넣어도 상관없는 파일(외부에 공개되어도 되는 파일)은 puclic/assets 에 넣으면 좋습니다.

(상세 설명)
src/assets/Logo.png 파일이 애플리케이션 로고와 같이 외부에 공개되어도 문제가 없는 정적 자산이라면, public/assets 폴더로 이동시키는 것이 좋습니다. 이렇게 하면 빌드 프로세스에서 해당 파일이 그대로 복사되어 public 폴더에 남아있고, 웹 서버에서 직접 접근할 수 있도록 관리할 수 있습니다.

추가적으로, public 폴더에 있는 파일들은 URL을 통해 쉽게 접근할 수 있기 때문에, 공개 가능한 파일이라면 이러한 접근 방식이 유리할 수 있습니다. 예를 들어, <img src="/assets/Logo.png" />와 같이 HTML에서 쉽게 참조할 수 있어 편리합니다.

이러한 접근 방식은 빌드 도구에서 파일을 번들링하거나 압축하는 과정을 거치지 않기 때문에, 사용자가 자주 접근하는 정적 자산에 대해 성능상의 이점을 제공할 수도 있습니다.

2024-10-06 05:08 UTC, minsekim1 commented on src/components/features/IntroductionPage/Introduction.tsx
> +        <Image w="full" h="463px" alt="Intro1" src={Intro1} />
public에 넣어도 상관없는 파일(외부에 공개되어도 되는 파일)은 puclic/assets 에 넣으면 좋습니다.

(상세 설명)
 <img src="/assets/Logo.png" /> 처럼 public로 옮기고 나서 import 하지 않고 바로 쓸 수 있습니다.

2024-10-06 05:09 UTC, minsekim1 commented on src/components/features/IntroductionPage/Introduction.tsx
> +        <Image w="full" h="463px" alt="Intro1" src={Intro1} />
다른 image들과 logo 파일도 바꾸어주세요

2024-10-06 05:14 UTC, minsekim1 requested changes
craco 설정 / css 처리 / 파일(assets)  관리 / 페이지 생성 부분 잘 보았습니다.

외부에 공개되어도 되는 파일 assets는  public에 넣으셔도 될 것 같아요.

이후에 더 나아가면 AWS S3 같은 이미지 저장소에 최적화(.avif로 변환) 하여 올리거나 cdn 을 활용하기도 합니다.

2024-10-07 05:42 UTC, jasper200207 commented on src/components/features/IntroductionPage/Introduction.tsx
> +        <Image w="full" h="463px" alt="Intro1" src={Intro1} />
Master에 이미 merge되어 있는 상태라 해당부분은 다음주 PR에 포함시켜도 괜찮을까요?

2024-10-07 10:17 UTC, minsekim1 commented on src/components/features/IntroductionPage/Introduction.tsx
> +        <Image w="full" h="463px" alt="Intro1" src={Intro1} />
넵! resolve해놓을게요!

2024-10-20 00:39 UTC, minsekim1 approved these changes

2024-10-20 00:39 UTC, merged